### ISSUE TITLE
Funciones Dashboard

### ISSUE THREAD

**Issue by CitlalliDMG** [CitlalliDMG/cdmx-2018-06-bc-core-am-data-dashboard#17]
- [x] Función computeStudentStats
   - [x] Redactar función
   - [x] Pasar test
- [x] Función generationStats
   - [x] Redactar función
   - [x] Pasar test
- [x] Función sortStudents
   - [x] Redactar función
   - [x] Pasar test
- [x] Función filterStudents
   - [x] Redactar función
   - [x] Pasar test

**Comment by jetzable** [comment]
Se completó función que regresa objeto con propiedad subtopics.
Se actualizaron test de funcion Sort y computeStudentStats
