### ISSUE TITLE
Actualizar README's

### ISSUE THREAD

**Issue by CitlalliDMG** [CitlalliDMG/cdmx-2018-06-bc-core-am-data-dashboard#18]
README UX
- [x] Agregar info sobre prueba de usuario
- [x] Agregar información sobre color
- [x] Agregar información sobre tipografía
- [x] Actualizar prototipo

README FRONT-END

- [x] Introducción
- [x] Preámbulo
- [x] Build status
- [x] Code style
- [x] Screenshots
- [x] Tech/framework usados
- [x] Features
- [x] Instalación
- [x] Archivos
- [x] SRC
- [x] UX
- [x] Tests
- [x] ¿Cómo usar el Data Dashboard?
- [x] Colaboradoras

**Comment by jetzable** [comment]
Se corrigió estilo de README UX.
