### ISSUE TITLE
Feedback Sprint 1 Datadashboard 

### ISSUE THREAD

**Issue by nerdale** [CitlalliDMG/cdmx-2018-06-bc-core-am-data-dashboard#3]
Hola @jetzable y @CitlalliDMG 
He estado revisando el proyecto y tengo algunos comentarios:

1. Felicitaciones por todo el trabajo de UX designer que hay detrás, se ve que lo tomaron en serio, me encantó que utilizaran marvel para poder interactuar con el flujo del prototipo, espero lo logren realizar lo más fiel posible :clap: 

2. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

3. Recuerden no olvidar el desarrollo orientado a test, vayan analizando lo que les pide poco a poco y corriendo los tests.

4. Les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

5. Ojo con los colores de Laboratoria, traten de buscar el manual de normas gráficas de Laboratoria o por último utilizar herramientas de Chrome como **colorzilla** (es un gotero que saca el código hexadecimal de los colores de una web)

Vamos comiencen luego con a darle forma al datadashboard :muscle:

**Comment by CitlalliDMG** [comment]
Hola @nerdale :smile: 
Muchas gracias por tu feedback, aplicaremos tus recomendaciones al desarrollo del proyecto

**Comment by jetzable** [comment]
Se analizó el feedback aplicandolo en el Sprint actual.
